name: Docs

on: [push, pull_request, workflow_dispatch]

env:
  FORCE_COLOR: 1

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
          allow-prereleases: true
          cache: pip
          cache-dependency-path: |
            setup.py
            doc/requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -r doc/requirements.txt
          python -m pip install -e .

      - name: Build documentation
        run: |
          make -C doc html

      - name: Upload documentation
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: doc/.build/html
